name: BonescraftLand
main: de.bonescraft.land.BonescraftLand
version: 1.7.0
api-version: '1.20'
author: Bonescraft
softdepend: [LuckPerms]
commands:
  land:
    description: Claim and manage land
    usage: /land <claim|unclaim|info|add|remove|list>
  playtime:
    description: Show playtime (monthly)
    usage: /playtime [player] [yyyy-MM]
